### ISSUE TITLE
Uncaught ReferenceError: corslite is not defined

### ISSUE THREAD

**Issue by muhamedoufi** [willmorejg/lrm-openrouteservice#8]
<pre>
 at e.route (L.Routing.OpenRouteService.js:52:4)
    at e.route (leaflet-routing-machine.js:16151:41)
    at e.onAdd (leaflet-routing-machine.js:15919:10)
    at e.addTo (Control.js:70:42)
    at (index):588:8
</pre>

my code snippet 
<pre>
// create the routing control and add it to the map
    var routCtrl = new L.Routing.control({
        waypoints:[
            L.latLng(18.0928, -15.9611),
            L.latLng(18.084189686687818, -15.966320625599066)
        ],
        // create a Leaflet routing control and add it to the map
        
        // router: L.Routing.graphHopper('b9aed0d1-2c8e-462b-8ea4-1d55a846ecb8')
        router:  new L.Routing.openrouteservice(api_key),

        // static\assets\vendor\lrm-graphhopper@1.3.0
    }).addTo(map);
</pre>

**Comment by CCRDude** [comment]
Same here
